spring.application.name=market-kacmoli-backend

spring.datasource.url=jdbc:mysql://avnadmin:AVNS_WP3yVK0AZfYhVBNOzvR@mysql-24ac93af-luisjanamuslika-4b95.l.aivencloud.com:24746/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_WP3yVK0AZfYhVBNOzvR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080